server.port: 8123
server.session.timeout: 360000 #10h

solon.app:
  name: "bcfadmin"
  group: "water_bcf"
  title: "BCF"

solon.cloud.water:
  server: "waterapi"
  config:
    load: "bcf.yml"


bcfadmin.user: admin
bcfadmin.password: SykSYLWN9WTpzCHq