server.port: 8123
server.session.timeout: 7200

solon.app:
  name: "bcfadmin"
  group: "water_bcf"
  title: "BCF"

solon.cloud.water:
  server: "waterapi"
  config:
    loadKey: "bcf.yml"


bcfadmin.user: admin
bcfadmin.password: SykSYLWN9WTpzCHq