server.port: 8124
server.session.timeout: 360000 #10h

solon.app:
  name: "bcfdock"
  group: "water_bcf"
  title: "跨系统通用管理平台"

solon.cloud.water:
  server: "waterapi:9371"
  config:
    load: "bcf.yml"