server.port: 8124
server.session.timeout: 7200

solon.app:
  name: "bcfdock"
  group: "water"
  title: "跨系统通用管理平台"

#water.host: water
#water.service.name: bcfdock
#water.service.secretKey: oYjS1xaM2oPfEyKc

solon.cloud.water:
  server: "water"
  config:
    loadGroup: "water_bcf"
    loadKey: "bcf.yml"